stages:
    - Pre-Build
    - Build
    - Deploy

# region global_settings ######################################################
# before_script:
#     - docker info
# image: registry.uwm-nm-te-capstone.com:8083/general/node-docker:latest
cache:
    paths:
        - node_modules/
# endregion global_settings ###################################################

# region job_templates ########################################################
.pre_build_base:
    stage: Pre-Build
    image: node:10.16.0-alpine
    before_script:
        - npm install
    when: on_success
# endregion job_templates #####################################################

# region Pre-Build ############################################################
Test:
    extends: .pre_build_base
    script:
        - npm test
# endregion Pre-Build #########################################################

# region Build ################################################################
.Build:
    stage: Build
    script:
        - docker login -u $DOCKER_REPO_USER -p $DOCKER_REPO_PASS registry.uwm-nm-te-capstone.com:8083
        - docker build -t registry.uwm-nm-te-capstone.com:8083/$CI_PROJECT_PATH:$CI_COMMIT_SHA -t registry.uwm-nm-te-capstone.com:8083/$CI_PROJECT_PATH:latest .
        - docker push registry.uwm-nm-te-capstone.com:8083/$CI_PROJECT_PATH:$CI_COMMIT_SHA
        - docker push registry.uwm-nm-te-capstone.com:8083/$CI_PROJECT_PATH:latest
    only:
        - master
    when: on_success
# endregion Build #############################################################

# region Deploy ###############################################################
.Deploy:
    stage: Deploy
    script:
        - bash deploy/deploy.sh
    only:
        - master
# endregion Deploy ############################################################
